name: Rename Files with Leading Zeros

on:
  push:
    branches:
      - main  # Или любая другая ветка, где вы хотите автоматизировать этот процесс

jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Важно для работы с историей

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Add leading zeros to filenames
        run: |
          import os
          import re
          from git import Repo

          repo = Repo('.')
          assert not repo.bare
          changed_files = [item.a_path for item in repo.index.diff(None)]

          def add_leading_zeros(filename):
              parts = filename.split('-')
              number = parts[0]
              padded_number = f'{int(number):03d}'  # Подгонка под три цифры, измените при необходимости
              new_filename = padded_number + '-' + '-'.join(parts[1:])
              os.rename(filename, new_filename)
              return new_filename

          for file in changed_files:
              if re.match(r'^\d+-', file):
                  new_name = add_leading_zeros(file)
                  repo.git.add(new_name)
                  repo.git.rm(file)

          if changed_files:
              repo.git.commit('-m', 'Automatically renamed files to include leading zeros')
              repo.git.push()

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
